export const activityOptions = [
  "Plank",
  "Stretching",
  "Muscle_Ups",
  "One_Hand_Pushups",
  "Single_Leg_Squats",
  "Archer_Pullups",
  "One_Hand_Pullups",
  "Power_Clean",
  "Power_Clean_and_Jerk",
  "Hang_Power_Clean",
  "Hang_Power_Clean_and_Jerk",
  "Pogo_Skips",
  "Scissors_Hop_Skips",
  "400m_Tempo_Run",
  "500m_Tempo_Run",
  "Sprint_Drills",
  "High_Knees_And_50m_Sprint",
  "High_Knees_And_100m_Sprint",
  "(100m run + 300m jog + 400m walk)",
  "(200m run + 600m jog + 400m walk)",
  "(300m run + 900m jog + 400m walk)",
  "(400m run + 1200m jog + 400m walk)",
  "(500m run + 1500m jog + 400m walk)",
  "100m_Time_Trial",
  "200m_Time_Trial",
  "300m_Time_Trial",
  "400m_Time_Trial",
  "500m_Time_Trial",
  "50m_Dash",
];

export const activityConditions = [
  "Rope_Assisted",
  "With_Support_Hand",
  "Negative"
];
